const library = [
    {
        "name": "kick",
        "start": 1,
        "sounds": [
            "MICRO KICK",
            "NT KICK",
            "NT KICK B",
            "NT KICK C",
            "NT KICK D",
            "LOCK KIK",
            "KICK GRIT",
            "KICK VERB",
            "KICK MID",
            "KICK BUMP",
            "KICK 9X9 DIRT",
            "KICK 9X9 DIRT B",
            "KICK 9X9 DIRT C",
            "KICK 9X9 DIRT D",
            "KICK 9X9 DIRT E",
            "KICK HARD",
            "KICK AIR",
            "KICK THUD",
            "AFTERPARTY KICK",
            "CARDIO KICK 1",
            "NT ALT KICK",
            "NT ALT KICK B",
            "NT ALT KICK C",
            "KICK DIRT",
            "KICK SUB",
            "KICK SP",
            "KICK FLUX",
            "KICK FLUX B",
            "KICK SUB B",
            "KICK OPEN",
            "BOOMER KICK"
        ]
    },
    {
        "name": "snare",
        "start": 100,
        "sounds": [
            "NT SNARE",
            "NT SNARE B",
            "NT SNARE C",
            "SNARE LO",
            "SNARE MID",
            "SNARE HI",
            "SNARE 6X6 1 ",
            "SNARE 6X6 2",
            "SNARE 6X6 3",
            "SNARE CLASSIC",
            "SNARE FAT",
            "SNARE SMACK",
            "SNARE BURST",
            "BRUSHY SNARE 1 ",
            "NT SNARE ALT",
            "NT SNARE ALT B ",
            "NT SNARE ALT C",
            "SNARE RIM",
            "SNARE PUNCH",
            "SNARE POP",
            "SNARE SNAP",
            "SNARE VINYL",
            "SNARE MP3K",
            "SNARE MINI BM",
            "SNARE VINYL B",
            "SNARE RES",
            "SNARE OPEN",
            "SNARE WOOD",
            "QUIK ROLL 3",
            "LONDON SNARE 2",
            "NT RIMSHOT",
            "NT RIMSHOT B",
            "NT RIMSHOT C",
            "RIM LO",
            "RIM MID",
            "RIM HI",
            "RIMSHOT DDDI",
            "RIMSHOT VINYL",
            "RIMSHOT 7X7 SP",
            "RIMSHOT DMX",
            "RIM DARK",
            "RIM SMACK",
            "RIM SNAP",
            "SIDEQUEST SNARE",
            "KNOW RIMSHOT I",
            "AKKOUNTANT RIM 2"
        ],
    },
    {
        "name": "cymb",
        "start": 200,
        "sounds": [
            "NT HH CLOSED ",
            "NT HH CLOSED B ",
            "NT HH CLOSED C ",
            "CLOSED HAT LO",
            "CLOSED HAT MID ",
            "CLOSED HAT HI",
            "CLOSED HAT PEDAL",
            "CLOSED HAT FOOT",
            "HAT CLOSED 9X9",
            "HAT CLOSED 6Х6",
            "HAT CLOSED 6X6",
            "HAT CLOSED 8X8",
            "CLOSED HAT LO B",
            "CLOSED HAT HI B",
            "CLOSED HAT AIR",
            "GOLDEN HAT I ",
            "SHINE HAT 4",
            "CRUNCH HAT 2",
            "NT HH OPEN ",
            "NT HH OPEN B ",
            "NT HH OPEN C",
            "OPEN HAT REAL ",
            "OPEN HAT DRIVE",
            "OPEN HAT METAL",
            "HAT OPEN 9X9",
            "HAT OPEN 5X5",
            "HAT OPEN 6X6",
            "HAT OPEN 8X8",
            "OPEN HAT LO",
            "OPEN HAT HI",
            "OPEN HAT AIR",
            "GOLDEN HAT I B",
            "BRUSH HAT 4",
            "LUCKY DBL HAT 2",
            "GIRTH OPEN HAT 3",
            "NT RIDE",
            "NT RIDE B",
            "RIDE DARK",
            "RIDE BRITE",
            "RIDE SAKATA",
            "CYMBAL MPI",
            "RIDE 7X7",
            "RIDE DARK B",
            "RIDE LITE",
            "RIDE BELL",
            "RIDE HI",
            "TOASTER BELL",
            "NT RIDE C",
            "CRASH",
            "CRASH 9X9",
            "CHINA 626",
            "SPLASH",
            "CRASH CYM",
            "80 GREAT CRASH"
        ]
    },
    {
        "name": "perc",
        "start": 300,
        "sounds": [
            "NT CLAP",
            "NT CLAP B",
            "NT CLAP C",
            "CLAP REAL",
            "CLAP HARD",
            "CLAP SNAP",
            "CLAP VINYL",
            "CLAP TRUMULATOR",
            "CLAP SP DISCO",
            "CLAP SP DISCO B",
            "CLAP DARK",
            "CLAP LITE",
            "CLAP AIR",
            "CLAP NOISE",
            "GOSPEL CLAP 3",
            "HOMECOMING CLAP",
            "DETROIT CLAP 2",
            "NT TAMBO",
            "NT TAMBO B",
            "NT TAMBO C",
            "HAND DRUM LO",
            "AGOGO",
            "BONGO MID 4",
            "HAND DRUM HI",
            "CONGA MID II",
            "TAMB",
            "MARACA",
            "BONGO HI",
            "GUIRO",
            "BONGO LO",
            "CLAVE",
            "CONGA LO",
            "CONGA HI",
            "CABASE LMI",
            "CABASA MP3K",
            "CABASA LNNDRUM",
            "SHAKER DMX",
            "TAMB B",
            "CLAVE B COWBELL",
            "SHAKER",
            "HERMES HIHAT 2",
            "LOWW CLAVE 1",
            "NT PERC",
            "NT PERC B",
            "NT PERC C",
            "TOM FAT",
            "TOM SKIN",
            "TOM ROUND LO",
            "TOM ROUND HI",
            "TOM SP",
            "TOM LNNDRUM",
            "TOM LO FLAM",
            "TOM MID",
            "TOM HI",
            "SWEET SHAKE I",
            "FUNCTION TOM 3",
            "HUNDOBELL PERC 2"
        ]
    },
    {
        "name": "bass",
        "start": 400,
        "sounds": [
            "NT BASS",
            "S95X ROUND",
            "TUBRO BASS",
            "E BASS ROUND",
            "BASIC",
            "MP3 SUB",
            "SYN A RE",
            "UPRIGHT SUB",
            "E BASS PICK",
            "THMP",
            "CAT ENVELOPE",
            "TB3X3 PUNCH",
            "UGGBASS",
            "E BASS PICK B",
            "PERFECT BASS",
            "PRODIGY SUB",
            "S95X SUB",
            "BASS THUB",
            "ROCKELBASS MID",
            "E BASS DIST",
            "OB SUB",
            "CX TONE",
            "BUZZ BASS",
            "ROCKELBASS SHORT",
            "MNO EVO FILTER",
            "SYNTH 4TH HIT",
            "THIRTY SEVEN SUB",
            "ORGA",
            "MUD",
            "REESE",
            "P.SIX SIMPLE",
            "S612 ELECTRIC",
            "AKUBASS MIDLONG",
            "MUD B",
            "WET BASS",
            "CS5 SQUARE",
            "S612 WARM",
            "ELEC BASS",
            "BOING",
            "ORGAN DX HOUSE",
            "REVY",
            "SDSV TOM",
            "DR SMPL WARM",
            "GROWLY",
            "ORGANISH",
            "TWO SIX 00 SMOOT",
            "PRODIGY PUNCH",
            "FLATE",
            "KAA WA BELL AIR",
            "SO ROUND",
            "DE-EX SOLID",
            "CHICAGO",
            "SUBD",
            "PHONEC GRR",
            "OVERDRIVE",
            "PRODIGY SQUARE",
            "TOCK",
            "WLOBB WOBB",
            "PUFF",
            "RUDE TWANG"
        ]
    },
    {
        "name": "melod",
        "start": 500,
        "sounds": [
            "BLUE",
            "PIANO S95X",
            "WURLI CLEAN",
            "MUTE STRATO",
            "CUTE EMU FLUTE",
            "ULTRA",
            "SQUICK",
            "CLAV 360 PHASER",
            "BABY CHORD",
            "BG VOCAL",
            "SKYLINE STRING",
            "OCTAVE STAB",
            "TRUMPET BREEZY",
            "SCARY VIBES",
            "SLY SYNTH CHORD",
            "EPIANO 360",
            "ORGAN DX VERB",
            "PLUCK HI BASS",
            "PLUCK HYBRID",
            "PROPHET PIANO",
            "EPIANO 360 BASS",
            "HOUSEORGAN DE-EX",
            "SOOTHE STRING",
            "CELLO PLUCKZ",
            "HIGH PAN",
            "SYNTH MICRO FUNK",
            "DR ORGAN CHORD",
            "LEADAFT",
            "SOOTHE STRONG",
            "SIMPLE TROMBONE",
            "CELLO 360",
            "FLUTE 360 FILTER",
            "ORGAN DX200 STAB",
            "WATERCHORD AM7",
            "SAD GUITAR",
            "HORN 360 ENGLISH",
            "STRINGS 360",
            "HOUSE CHORD EM7",
            "UPRIGHT CHORD",
            "EXOTIC PLUCK",
            "SKY LEAD",
            "STRINGS DR",
            "LIQUID CHORD EM7",
            "CHORDY F9SUS4",
            "BROKEN BELL PERC",
            "PLING CHORD",
            "S612 VERB HIT",
            "DR",
            "VOX S612 DARK",
            "SITAR ONE SHOT",
            "LOOK ORGAN",
            "THIRTY 7 STAB",
            "BUZZ DELAY",
            "VOX S612 EH",
            "GUZHENG",
            "NT CHORDY",
            "FX BIRDS TAPE",
            "VOX S612 GATED",
            "O3D",
            "SEARCH CHORD"
        ]
    }
];

